### ISSUE TITLE
Initial setup challenges - KeyError: 'workspace'

### ISSUE THREAD

**Issue by slaurel** [adamgignac/brain#13]
After going through the installation and opening the webui, I see the SystemMap screen.
Log in, and create a workspace.
Click through into the new workspace, and click "Add Item", and get KeyError 'workspace' in workspaces/None-test/items/add/

Not sure whether this is a documentation step that could be improved, which I didn't intuit - or incomplete code for setting up new workspaces?

<pre>KeyError at /workspaces/None-test/items/add/

'workspace'

Request Method: 	GET
Request URL: 	http://localhost:8000/workspaces/None-test/items/add/
Django Version: 	3.0
Exception Type: 	KeyError
Exception Value: 	

'workspace'

Exception Location: 	/home/dmaxwell/brain/brain/mapping/views.py in get_context_data, line 78
Python Executable: 	/home/dmaxwell/.local/share/virtualenvs/brain-xUlOsp7R/bin/python
Python Version: 	3.7.5
Python Path: 	

['/home/dmaxwell/brain/brain',
 '/home/dmaxwell/.local/share/virtualenvs/brain-xUlOsp7R/lib/python37.zip',
 '/home/dmaxwell/.local/share/virtualenvs/brain-xUlOsp7R/lib/python3.7',
 '/home/dmaxwell/.local/share/virtualenvs/brain-xUlOsp7R/lib/python3.7/lib-dynload',
 '/usr/lib/python3.7',
 '/home/dmaxwell/.local/share/virtualenvs/brain-xUlOsp7R/lib/python3.7/site-packages']

Server time: 	Thu, 2 Jan 2020 15:08:12 +0000
</pre>

**Comment by adamgignac** [comment]
Looks like it was a typo in the urls.py file. Should be fixed on master now.

**Comment by slaurel** [comment]
Master's last update was Jun 21, 2019. The change is not showing up yet. Thanks.

**Comment by slaurel** [comment]
Okay - I was looking at the wrong urls.py.  Updating that did make it possible to click on the 'add item' button without error.

However, now on the form to add an item, the 'Type' drop down list is populated with a single entry "----------" - which is not accepted by the form, which says 'Please select an item in this list'.

I can't rename this issue - do you want to continue here, or start a new one, since this isn't about Keyspace Error anymore. ?

**Comment by slaurel** [comment]
Nevermind - unfamiliarity with workflow - have to go to 'manage types' first, and create a type.
Probably worth adding a more informative error if there are no types in the system - or prevent getting to the 'add item' page if there are no types configured yet.
